title: Jordan Sternberg Consulting
description: Revenue operations, sales strategy, and business scaling consulting
theme: jekyll-theme-minimal
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
